[versions]
agp = "8.9.0"
compiler = "4.16.0"
core = "1.15.0"
exoplayer = "2.19.1"
gson = "2.10.1"
jacksonDatabind = "2.18.2"
jaudiotagger = "2.0.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
media = "1.7.0"
media3Exoplayer = "1.5.1"
okhttp = "3.10.0"
overscrollDecorAndroid = "1.1.1"
paginate = "1.0.0"
palette = "1.0.0"
picasso = "2.8"
sdpAndroid = "1.1.1"
shimmer = "0.5.0"
slidingrootnav = "v1.1.1"
sspAndroid = "1.1.1"
swiperefreshlayout = "1.2.0-alpha01"
ffmpegandroid = "0.3.2"

[libraries]
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
core = { module = "androidx.core:core", version.ref = "core" }
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "compiler" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jacksonDatabind" }
jaudiotagger = { module = "org.jaudiotagger:jaudiotagger", version.ref = "jaudiotagger" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
media = { module = "androidx.media:media", version.ref = "media" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3Exoplayer" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Exoplayer" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
overscroll-decor-android = { module = "io.github.everythingme:overscroll-decor-android", version.ref = "overscrollDecorAndroid" }
paginate = { module = "com.github.markomilos:paginate", version.ref = "paginate" }
palette = { module = "androidx.palette:palette", version.ref = "palette" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
slidingrootnav = { module = "com.github.yarolegovich:SlidingRootNav", version.ref = "slidingrootnav" }
ssp-android = { module = "com.intuit.ssp:ssp-android", version.ref = "sspAndroid" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
ffmpegandroid = { group = "com.writingminds", name = "FFmpegAndroid", version.ref = "ffmpegandroid" }

# Media3 Exoplayer related dependencies
[bundles]
media3Exoplayer = ["media3-exoplayer", "media3-ui", "media3-exoplayer-dash"]


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

